config/routes.rb
Rails.application.routes.draw do
  get 'books/index'
  get 'demo/index'
  get 'demo/coba'


  get 'home/index'
  get 'home/iseng'
  get 'home/page'
  get 'home/keren'

  resources :books
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/author.rb
class Author < ApplicationRecord
  has_many :books

  def self.male_author
    where("gender != 'Female'")
  end

  def self.oldest
    order(age: :desc)
  end

  def self.youngest
    order(age: :asc).pluck(:name, :age)
  end

  def self.male_author_oldest
    male_author.oldest
  end

  def self.male_youngest
    male_author.youngest
  end
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :author

  def self.cheaper
    order(price: :asc).pluck(:price, :title)
  end

  def self.expensive_book
    where('price > 300000')
  end

  def self.equal_more(price)
    where('price >= ?', price)
  end

  def self.thin
    where('page < 100')
  end

  def self.thick
    where('page >= 500')
  end

  def self.thin_cheaper
    thin.cheaper
  end

  def self.thick_expensive
    thick.expensive_book
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def index
    @books = Book.all
    #kalau mau buat API dibawah ini
    #render json: {
    #  value: @books,
    #  messages: 'Success'
    #}, status: 200
  end

  def show
    id = params[:id]
    @book = Book.find(id)
    #render plain: @book.title
  end

  def new

  end

  def create
  end

  def edit
  end

  def update
  end

  def destroy
  end
end

app/controllers/demo_controller.rb
class DemoController < ApplicationController
  def index
  end

  def coba
    redirect_to controller: 'home', action: 'iseng'
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def iseng
    render plain: 'Iseng - iseng aja nih'
  end

  def page
    render 'landing'
  end

  def keren
    render 'landing'
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/demo_helper.rb
module DemoHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/books/index.html.erb
<table>
    <tr>
        <td>Title</td>
        <td>Price</td>
        <td>Page</td>
        <td>Description</td>
        <td>Action</td>
    <tr>
    <% @books.each do |buku| %>
        <tr>
            <td><%= buku.title %></td>
            <td><%= buku.price %></td>
            <td><%= buku.page %></td>
            <td><%= buku.description %></td>
            <td><%= link_to  "Show", book_path(buku) %></td>
        <tr>
    <% end %>
</table>

app/views/books/show.html.erb
Title : <%= @book.title %><br>
Price : <%= @book.price %><br>
Page : <%= @book.page %><br>
Description : <%= @book.description %><br><br><br>
<%= link_to  "Back to List Books", books_path %>

app/views/demo/index.html.erb
<h1>Demo#index</h1>
<p>Find me in app/views/demo/index.html.erb</p>

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>

app/views/home/landing.html.erb
<h1>Landing Page # Home </h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MinLib</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>